INSERT INTO TBPPKV005
(
	 ASK_ID
	,RSHP_ID
	,PRVDR_CD
	,HASH_DID
	,TTP_ID
	,MRG_NM
	,MRG_SSN
	,CRT_PGM_ID
	,CRT_DT
)
SELECT 
	 A.ASK_ID
	,A.RSHP_ID
	,A.PRVDR_CD
	,A.HASH_DID
	,A.TTP_ID
	,A.MRG_NM
	,A.MRG_SSN
	,'{crt_pgm_id}'
,SYSDATE
FROM TBPPKV003 A , TBPPKV004 B
WHERE 1=1
AND A.ASK_ID = B.ASK_ID
AND A.RSHP_ID = B.RSHP_ID
AND A.PRVDR_CD = B.PRVDR_CD
AND A.HASH_DID = B.HASH_DID
AND A.ASK_ID = '{ask_id}'
AND A.RSHP_ID = '{rshp_id}'
;