
MERGE INTO TBPPKV003 A
USING (
		SELECT
			 ? ASK_ID
			,? RSHP_ID
			,? PRVDR_CD
			,? MRG_NM
			,? MRG_SSN
			,? TTP_ID
			,? HASH_DID
			,'HashJob' CRT_PGM_ID
			,sysdate CRT_DT
		 FROM DUAL
	   ) B
ON
	( A.ASK_ID      = B.ASK_ID
	  AND A.RSHP_ID     = B.RSHP_ID
	  AND A.PRVDR_CD    = B.PRVDR_CD
	  AND A.MRG_NM = B.MRG_NM
	  AND A.MRG_SSN = B.MRG_SSN
	  AND A.TTP_ID = B.TTP_ID
	  AND A.HASH_DID = B.HASH_DID
	)	 
WHEN NOT MATCHED THEN 
INSERT (A.ASK_ID,A.RSHP_ID,A.PRVDR_CD,A.MRG_NM,A.MRG_SSN,A.TTP_ID,A.HASH_DID,A.CRT_PGM_ID,A.CRT_DT) 
VALUES (B.ASK_ID,B.RSHP_ID,B.PRVDR_CD,B.MRG_NM,B.MRG_SSN,B.TTP_ID,B.HASH_DID,B.CRT_PGM_ID,B.CRT_DT)

